spring:
  cloud:
    gateway:
      routes:
        # 路由数组[路由 就是指定当请求满足什么条件的时候转到哪个微服务]
        - id: application  # 当前路由的标识, 要求唯一
          uri: lb://application # lb指的是从 nacos 中按照名称获取微服务,并遵循负载均衡策略
          predicates:
            - Path=/application/**  # 当请求路径满足Path指定的规则时,才进行路由转发
          filters:
            - StripPrefix=1
        - id: platform
          uri: lb://platform
          predicates:
            - Path=/platform/**
          filters:
            - StripPrefix=1